services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: secret_front
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - /app/node_modules
      - type: bind
        source: ./
        target: /app