"use client";
import { BrowserRouter as Router } from 'react-router-dom';
/*
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}*/

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <Router>
      <body>{children}</body>
    </Router>
    </html>
    
  )
}
